### ISSUE TITLE
Parse initial content for already typed placeholders

### ISSUE THREAD

**Issue by sotaan** [jspaine/quill-placeholder-module#1]
I don't know if I missed something or use Quill the wrong way.
When there is initial content passed to my instance, I don't have my placeholders parsed as corresponding `PlaceholderBlot`.
Do you have an idea of how implement that easily?

**Comment by jspaine** [comment]
Hi, how are you passing the initial content? I used react-quill and didn't have a problem, looking at it it uses `quill.clipboard.dangerouslyPasteHTML` to set the content. Otherwise you'd probably have to convert it to a delta to use `quill.setContents`.

I added an example to the codepen demo, just uncomment the last line to try it.

**Comment by sotaan** [comment]
I use `vue-quill-editor`.
I have placeholder in this type of form:
```html
<p> something is here </p>
<p> #{foo} #{bar} </p>
....
```
I ended up using `getContents()` and parsing Delta using a regex.
Almost finished, I’ll post something in the morning when I’m on my desk.
